components {
  id: "Block_Normal"
  component: "/Scripts/Projectile/Absorb/Absorb_Normal.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"death\"\n"
  "mask: \"life\"\n"
  "mask: \"shield\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"coll\"\n"
  "  }\n"
  "  data: 43.705227\n"
  "  data: 32.64382\n"
  "  data: 33.4\n"
  "}\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"Absorb\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Sprites/Projectile/Projectile.atlas\"\n"
  "}\n"
  ""
}
